// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

// Import user types
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

library OptionalSystemHooks {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "world", name: "OptionalSystemHo", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462776f726c640000000000000000004f7074696f6e616c53797374656d486f);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0000000100000000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (address, bytes32, bytes32)
  Schema constant _keySchema = Schema.wrap(0x00540300615f5f00000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (bytes21[])
  Schema constant _valueSchema = Schema.wrap(0x00000001b6000000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](3);
    keyNames[0] = "player";
    keyNames[1] = "systemId";
    keyNames[2] = "callDataHash";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](1);
    fieldNames[0] = "hooks";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config (using the specified store).
   */
  function register(IStore _store) internal {
    _store.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get hooks.
   */
  function getHooks(
    address player,
    ResourceId systemId,
    bytes32 callDataHash
  ) internal view returns (bytes21[] memory hooks) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes21());
  }

  /**
   * @notice Get hooks.
   */
  function _getHooks(
    address player,
    ResourceId systemId,
    bytes32 callDataHash
  ) internal view returns (bytes21[] memory hooks) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes21());
  }

  /**
   * @notice Get hooks (using the specified store).
   */
  function getHooks(
    IStore _store,
    address player,
    ResourceId systemId,
    bytes32 callDataHash
  ) internal view returns (bytes21[] memory hooks) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    bytes memory _blob = _store.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes21());
  }

  /**
   * @notice Get hooks.
   */
  function get(
    address player,
    ResourceId systemId,
    bytes32 callDataHash
  ) internal view returns (bytes21[] memory hooks) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes21());
  }

  /**
   * @notice Get hooks.
   */
  function _get(
    address player,
    ResourceId systemId,
    bytes32 callDataHash
  ) internal view returns (bytes21[] memory hooks) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes21());
  }

  /**
   * @notice Get hooks (using the specified store).
   */
  function get(
    IStore _store,
    address player,
    ResourceId systemId,
    bytes32 callDataHash
  ) internal view returns (bytes21[] memory hooks) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    bytes memory _blob = _store.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes21());
  }

  /**
   * @notice Set hooks.
   */
  function setHooks(address player, ResourceId systemId, bytes32 callDataHash, bytes21[] memory hooks) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((hooks)));
  }

  /**
   * @notice Set hooks.
   */
  function _setHooks(address player, ResourceId systemId, bytes32 callDataHash, bytes21[] memory hooks) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((hooks)));
  }

  /**
   * @notice Set hooks (using the specified store).
   */
  function setHooks(
    IStore _store,
    address player,
    ResourceId systemId,
    bytes32 callDataHash,
    bytes21[] memory hooks
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    _store.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((hooks)));
  }

  /**
   * @notice Set hooks.
   */
  function set(address player, ResourceId systemId, bytes32 callDataHash, bytes21[] memory hooks) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((hooks)));
  }

  /**
   * @notice Set hooks.
   */
  function _set(address player, ResourceId systemId, bytes32 callDataHash, bytes21[] memory hooks) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((hooks)));
  }

  /**
   * @notice Set hooks (using the specified store).
   */
  function set(
    IStore _store,
    address player,
    ResourceId systemId,
    bytes32 callDataHash,
    bytes21[] memory hooks
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    _store.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((hooks)));
  }

  /**
   * @notice Get the length of hooks.
   */
  function lengthHooks(address player, ResourceId systemId, bytes32 callDataHash) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 21;
    }
  }

  /**
   * @notice Get the length of hooks.
   */
  function _lengthHooks(address player, ResourceId systemId, bytes32 callDataHash) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 21;
    }
  }

  /**
   * @notice Get the length of hooks (using the specified store).
   */
  function lengthHooks(
    IStore _store,
    address player,
    ResourceId systemId,
    bytes32 callDataHash
  ) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    uint256 _byteLength = _store.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 21;
    }
  }

  /**
   * @notice Get the length of hooks.
   */
  function length(address player, ResourceId systemId, bytes32 callDataHash) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 21;
    }
  }

  /**
   * @notice Get the length of hooks.
   */
  function _length(address player, ResourceId systemId, bytes32 callDataHash) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 21;
    }
  }

  /**
   * @notice Get the length of hooks (using the specified store).
   */
  function length(
    IStore _store,
    address player,
    ResourceId systemId,
    bytes32 callDataHash
  ) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    uint256 _byteLength = _store.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 21;
    }
  }

  /**
   * @notice Get an item of hooks.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemHooks(
    address player,
    ResourceId systemId,
    bytes32 callDataHash,
    uint256 _index
  ) internal view returns (bytes21) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 21, (_index + 1) * 21);
      return (bytes21(_blob));
    }
  }

  /**
   * @notice Get an item of hooks.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemHooks(
    address player,
    ResourceId systemId,
    bytes32 callDataHash,
    uint256 _index
  ) internal view returns (bytes21) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 21, (_index + 1) * 21);
      return (bytes21(_blob));
    }
  }

  /**
   * @notice Get an item of hooks (using the specified store).
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemHooks(
    IStore _store,
    address player,
    ResourceId systemId,
    bytes32 callDataHash,
    uint256 _index
  ) internal view returns (bytes21) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    unchecked {
      bytes memory _blob = _store.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 21, (_index + 1) * 21);
      return (bytes21(_blob));
    }
  }

  /**
   * @notice Get an item of hooks.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItem(
    address player,
    ResourceId systemId,
    bytes32 callDataHash,
    uint256 _index
  ) internal view returns (bytes21) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 21, (_index + 1) * 21);
      return (bytes21(_blob));
    }
  }

  /**
   * @notice Get an item of hooks.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItem(
    address player,
    ResourceId systemId,
    bytes32 callDataHash,
    uint256 _index
  ) internal view returns (bytes21) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 21, (_index + 1) * 21);
      return (bytes21(_blob));
    }
  }

  /**
   * @notice Get an item of hooks (using the specified store).
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItem(
    IStore _store,
    address player,
    ResourceId systemId,
    bytes32 callDataHash,
    uint256 _index
  ) internal view returns (bytes21) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    unchecked {
      bytes memory _blob = _store.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 21, (_index + 1) * 21);
      return (bytes21(_blob));
    }
  }

  /**
   * @notice Push an element to hooks.
   */
  function pushHooks(address player, ResourceId systemId, bytes32 callDataHash, bytes21 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Push an element to hooks.
   */
  function _pushHooks(address player, ResourceId systemId, bytes32 callDataHash, bytes21 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Push an element to hooks (using the specified store).
   */
  function pushHooks(
    IStore _store,
    address player,
    ResourceId systemId,
    bytes32 callDataHash,
    bytes21 _element
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    _store.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Push an element to hooks.
   */
  function push(address player, ResourceId systemId, bytes32 callDataHash, bytes21 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Push an element to hooks.
   */
  function _push(address player, ResourceId systemId, bytes32 callDataHash, bytes21 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Push an element to hooks (using the specified store).
   */
  function push(IStore _store, address player, ResourceId systemId, bytes32 callDataHash, bytes21 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    _store.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Pop an element from hooks.
   */
  function popHooks(address player, ResourceId systemId, bytes32 callDataHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 21);
  }

  /**
   * @notice Pop an element from hooks.
   */
  function _popHooks(address player, ResourceId systemId, bytes32 callDataHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 21);
  }

  /**
   * @notice Pop an element from hooks (using the specified store).
   */
  function popHooks(IStore _store, address player, ResourceId systemId, bytes32 callDataHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    _store.popFromDynamicField(_tableId, _keyTuple, 0, 21);
  }

  /**
   * @notice Pop an element from hooks.
   */
  function pop(address player, ResourceId systemId, bytes32 callDataHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 21);
  }

  /**
   * @notice Pop an element from hooks.
   */
  function _pop(address player, ResourceId systemId, bytes32 callDataHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 21);
  }

  /**
   * @notice Pop an element from hooks (using the specified store).
   */
  function pop(IStore _store, address player, ResourceId systemId, bytes32 callDataHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    _store.popFromDynamicField(_tableId, _keyTuple, 0, 21);
  }

  /**
   * @notice Update an element of hooks at `_index`.
   */
  function updateHooks(
    address player,
    ResourceId systemId,
    bytes32 callDataHash,
    uint256 _index,
    bytes21 _element
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 21), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update an element of hooks at `_index`.
   */
  function _updateHooks(
    address player,
    ResourceId systemId,
    bytes32 callDataHash,
    uint256 _index,
    bytes21 _element
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 21), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update an element of hooks (using the specified store) at `_index`.
   */
  function updateHooks(
    IStore _store,
    address player,
    ResourceId systemId,
    bytes32 callDataHash,
    uint256 _index,
    bytes21 _element
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      _store.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 21), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update an element of hooks at `_index`.
   */
  function update(
    address player,
    ResourceId systemId,
    bytes32 callDataHash,
    uint256 _index,
    bytes21 _element
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 21), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update an element of hooks at `_index`.
   */
  function _update(
    address player,
    ResourceId systemId,
    bytes32 callDataHash,
    uint256 _index,
    bytes21 _element
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 21), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update an element of hooks (using the specified store) at `_index`.
   */
  function update(
    IStore _store,
    address player,
    ResourceId systemId,
    bytes32 callDataHash,
    uint256 _index,
    bytes21 _element
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      _store.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 21), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(address player, ResourceId systemId, bytes32 callDataHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(address player, ResourceId systemId, bytes32 callDataHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Delete all data for given keys (using the specified store).
   */
  function deleteRecord(IStore _store, address player, ResourceId systemId, bytes32 callDataHash) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    _store.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Tightly pack dynamic data lengths using this table's schema.
   * @return _encodedLengths The lengths of the dynamic fields (packed into a single bytes32 value).
   */
  function encodeLengths(bytes21[] memory hooks) internal pure returns (EncodedLengths _encodedLengths) {
    // Lengths are effectively checked during copy by 2**40 bytes exceeding gas limits
    unchecked {
      _encodedLengths = EncodedLengthsLib.pack(hooks.length * 21);
    }
  }

  /**
   * @notice Tightly pack dynamic (variable length) data using this table's schema.
   * @return The dynamic data, encoded into a sequence of bytes.
   */
  function encodeDynamic(bytes21[] memory hooks) internal pure returns (bytes memory) {
    return abi.encodePacked(EncodeArray.encode((hooks)));
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(bytes21[] memory hooks) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData;
    EncodedLengths _encodedLengths = encodeLengths(hooks);
    bytes memory _dynamicData = encodeDynamic(hooks);

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(
    address player,
    ResourceId systemId,
    bytes32 callDataHash
  ) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(uint160(player)));
    _keyTuple[1] = ResourceId.unwrap(systemId);
    _keyTuple[2] = callDataHash;

    return _keyTuple;
  }
}
